---

- hosts: controller-nodes
  roles:
    - role: env-controller

- hosts: compute-nodes
  roles:
    - role: env-nodes

- hosts: controller-nodes
  roles:
    - role: keystoneserver
      
- hosts: controller-nodes
  roles:
    - role: keystone_population
      
# - hosts: storage-nodes
#   roles: 
#     - role: glanceserver

# - hosts: storage-nodes
#   roles: 
#     - role: glance_population

# - hosts: controller-nodes
#   roles:
#     - role: novaserver

# - hosts: compute-nodes
#   roles:
#     - role: novacompute

# - hosts: controller-nodes
#   roles:
#    - role: neutronserver

# - hosts: network-nodes
#   roles:
#     - role: neutron-agents

# - hosts: network-nodes
#   roles:
#     - role: openvswitch

# - hosts: compute-nodes
#   roles:
#     - role: neutron-agents-compute

# - hosts: controller-nodes
#   roles:
#     - role: horizon

# - hosts: controller-nodes
#   roles:
#     - role: cinderserver

# - hosts: storage-nodes
#   roles:
#     - role: cindervolume

# - hosts: controller-nodes
#   roles:
#     - role: restart-services
