---
# tasks file for env-controller
- name: install chrony
  include_role:
    name: fahlke.chrony
  vars:
    chrony_cfg_servers: [ 'pool 0.europe.pool.ntp.org' ]
    chrony_cfg_serveroptions: 'offline iburst'
    chrony_cfg_allows: ['127.0.0.1', '::1', '{{ admin_subnet }}' ]

- name: install common softwares
  include_role:
    name: infracommon

- name: install dbserver
  include_role:
    name: dbserver

# - hosts: controller-nodes
#   roles:
#     - role: dbserver_population

- name: install rabbitserver
  include_role:
    name: rabbitserver

- name: install memcached
  include_role:
    name: memcached